[versions]
awaitility = "4.2.2"
azure-storage-blob = "12.25.4"
gradleOci-junitJupiter = "0.6.0"
hivemq-extensionSdk = "4.7.5"
jetbrains-annotations = "24.1.0"
junit-jupiter = "5.10.0"
logback = "1.5.10"
mockito = "5.11.0"
owner = "1.0.12"
testcontainers = "1.19.8"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
azure-storage-blob = { module = "com.azure:azure-storage-blob", version.ref = "azure-storage-blob" }
gradleOci-junitJupiter = { module = "io.github.sgtsilvio:gradle-oci-junit-jupiter", version.ref = "gradleOci-junitJupiter" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
owner-java8 = { module = "org.aeonbits.owner:owner-java8", version.ref = "owner" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:hivemq", version.ref = "testcontainers" }
testcontainers-toxiproxy = { module = "org.testcontainers:toxiproxy", version.ref = "testcontainers" }

[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
hivemq-extension = { id = "com.hivemq.extension", version = "3.2.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.16.0" }
